export const CONSTANTS = {
  BCRYPT_ROUNDS: 12,
  OTP_LENGTH: 6,
  MAX_FILE_SIZE: 5 * 1024 * 1024, // 5MB
  ALLOWED_IMAGE_TYPES: ["image/jpeg", "image/png", "image/webp"],
  MAX_ITEM_PHOTOS: 5,
  DEFAULT_PAGE_SIZE: 10,
  MAX_PAGE_SIZE: 50,
  SUPPORTED_LANGUAGES: ["en", "fr"],
  DEFAULT_LANGUAGE: "en",
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER: 500,
};